version: 2.1
orbs:
  trivy: gotooooo/trivy@0.0.2
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - setup_remote_docker
      - trivy/scan_an_image:
          exit-code: 1
          image: 'nginx:latest'
          no-progress: true
          severity: 'HIGH,CRITICAL'
workflows:
  use-my-orb:
    jobs:
      - build
    
